baseURL = "https://www.franklinguevara.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Franklin Guevara"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I'm Franklin Guevara"
author = "Franklin Guevara"
#copyright = "2020-2021"
description = "Technology Enthusiast"
profilePicture = "images/shortme.png"
keywords = ""
favicon = "favicons/favicon-16x16.png"
# example ["css/custom.css"]
customCss = customCss = ["css/style.css", "css/markupHighlight.css"]
# example ["js/anatole-header.js", "anatole-theme-switcher.js", "medium-zoom.js"]
customJs = ["js/anatole-header.js", "anatole-theme-switcher.js", "medium-zoom.js"] 
mainSections = ["post"]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mgerelgb"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/franklin-guevara-20566875/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/guevarafranklin"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/tecguevara/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:frank@franklinguevara.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"
